"""Deterministic Markdown projection of authoritative application manifests."""

from __future__ import annotations

from pathlib import Path, PurePath

from career_agent.models.application import (
    ApplicationManifest,
    ApplicationStage,
    RecruitingEventKind,
)
from career_agent.models.submission import SubmissionStatus
from career_agent.services.opportunities import OpportunityService
from career_agent.storage.atomic import atomic_write_bytes
from career_agent.storage.paths import safe_resolve
from career_agent.storage.repository import ApplicationRepository

_HEADER = (
    "<!-- Generated by career pipeline build. Do not edit. -->\n"
    "# Career Pipeline\n\n"
    "| Application ID | Opportunity ID | Company | Role | Display phase | "
    "Application stage | Submission status | Outcome | Next action | "
    "Evidence limitations |\n"
    "|---|---|---|---|---|---|---|---|---|---|\n"
)


def _cell(value: str) -> str:
    return " ".join(value.replace("|", "\\|").splitlines()).strip() or "—"


def _display_phase(application: ApplicationManifest) -> str:
    if application.outcome is not None:
        return application.outcome.outcome.value
    if application.submission_status is SubmissionStatus.UNCERTAIN:
        return "submission_uncertain"
    if application.stage in {ApplicationStage.PREPARING, ApplicationStage.READY_FOR_REVIEW}:
        relevant = [
            event.kind
            for event in sorted(application.events, key=lambda event: event.occurred_at)
            if event.kind in {RecruitingEventKind.INTERVIEW, RecruitingEventKind.OFFER}
        ]
        if relevant:
            return relevant[-1].value
    return application.stage.value


def _next_action(application: ApplicationManifest) -> str:
    if application.outcome is not None or application.stage is ApplicationStage.CLOSED:
        return "none"
    if application.submission_status is SubmissionStatus.UNCERTAIN:
        return "resolve uncertain submission"
    if application.submission_status is SubmissionStatus.IN_PROGRESS:
        return "verify employer response"
    if application.events and application.events[-1].kind is RecruitingEventKind.OFFER:
        return "review offer"
    return {
        ApplicationStage.PREPARING: "prepare application materials",
        ApplicationStage.READY_FOR_REVIEW: "review final submission",
        ApplicationStage.APPROVED: "submit approved application",
        ApplicationStage.APPLYING: "verify employer response",
        ApplicationStage.SUBMITTED: "monitor employer response",
        ApplicationStage.CLOSED: "none",
    }[application.stage]


def _limitations(application: ApplicationManifest) -> str:
    values = {
        limitation
        for attempt in application.attempts
        for claim in attempt.evidence
        for limitation in claim.limitations
    }
    return "; ".join(sorted(values)) or "—"


def build_pipeline(root: Path) -> str:
    """Render pipeline Markdown without using the existing projection as input."""

    resolved_root = root.resolve(strict=False)
    repository = ApplicationRepository(resolved_root)
    opportunities = OpportunityService(root)
    rows: list[str] = []
    manifest_paths = sorted((resolved_root / "applications").glob("APP-*/manifest.json"))
    applications = tuple(repository.load(path.parent.name) for path in manifest_paths)
    for application in sorted(applications, key=lambda item: item.application_id):
        opportunity = opportunities.get(application.opportunity_id)
        outcome = application.outcome.outcome.value if application.outcome is not None else "—"
        cells = (
            application.application_id,
            application.opportunity_id,
            opportunity.company,
            opportunity.title,
            _display_phase(application),
            application.stage.value,
            application.submission_status.value,
            outcome,
            _next_action(application),
            _limitations(application),
        )
        rows.append("| " + " | ".join(_cell(value) for value in cells) + " |\n")
    return _HEADER + "".join(rows)


def write_pipeline(root: Path) -> Path:
    """Atomically replace the disposable pipeline projection."""

    path = safe_resolve(root.resolve(strict=False), PurePath("pipeline.md"))
    atomic_write_bytes(path, build_pipeline(root).encode("utf-8"))
    return path
