from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

from typer.testing import CliRunner

from career_agent.cli import app
from career_agent.config import initialize_workspace
from career_agent.projections.pipeline import build_pipeline, write_pipeline
from career_agent.services.payloads import PayloadService
from career_agent.services.submissions import ObservedEvidence, SubmissionService

from .documents.test_release import setup_workspace
from .test_submission_service import approved_submission

runner = CliRunner()
NOW = datetime(2026, 9, 18, 20, 30, tzinfo=UTC)


def test_pipeline_is_a_deterministic_disposable_projection(tmp_path: Path) -> None:
    root = tmp_path / "workspace"
    application_id, _ = setup_workspace(root)
    expected = (
        "<!-- Generated by career pipeline build. Do not edit. -->\n"
        "# Career Pipeline\n\n"
        "| Application ID | Opportunity ID | Company | Role | Display phase | "
        "Application stage | Submission status | Outcome | Next action | "
        "Evidence limitations |\n"
        "|---|---|---|---|---|---|---|---|---|---|\n"
        f"| {application_id} | OPP-2026-0001 | Example / Labs | Senior Product Manager | "
        "preparing | preparing | none | — | prepare application materials | — |\n"
    )

    rendered = build_pipeline(root)
    first_path = write_pipeline(root)
    first_bytes = first_path.read_bytes()
    first_path.unlink()
    (root / "applications" / "index.json").unlink()
    second_path = write_pipeline(root)

    assert rendered == expected
    assert first_bytes == expected.encode("utf-8")
    assert second_path.read_bytes() == first_bytes


def test_pipeline_build_cli_writes_only_the_projection(tmp_path: Path) -> None:
    root = tmp_path / "workspace"
    initialize_workspace(root)
    setup_workspace(root)

    result = runner.invoke(
        app,
        ["pipeline", "build", "--json"],
        env={"CAREER_WORKSPACE": str(root)},
    )

    assert result.exit_code == 0, result.output
    assert (root / "pipeline.md").read_text(encoding="utf-8") == build_pipeline(root)


def test_pipeline_derives_uncertainty_and_evidence_limitations(tmp_path: Path) -> None:
    root = tmp_path / "workspace"
    application_id, submission_id, approval_id = approved_submission(root)
    payload = PayloadService(root).load(application_id, submission_id)
    service = SubmissionService(root)
    service.begin(
        application_id,
        submission_id,
        approval_id,
        observed_payload_digest=PayloadService.digest(payload),
        browser_state_verified=True,
        browser_state_reference="browser-session-1#final-review",
        now=NOW,
    )
    service.observe(
        application_id,
        submission_id,
        ObservedEvidence(
            claim_id="portal-timeout",
            source_reference="browser-session-1#timeout",
            observed_at=NOW,
            confidence=0.5,
            limitations=("employer response timed out",),
            result="uncertain",
        ),
    )

    rendered = build_pipeline(root)

    assert "| submission_uncertain | applying | uncertain |" in rendered
    assert "| resolve uncertain submission | employer response timed out |" in rendered
